source 'https://bitbucket.org/omegarinc/cocoapods-specs.git' # private spec repo
source 'https://github.com/CocoaPods/Specs.git' # master cocoapods spec repo

use_frameworks!

target 'ORCommonUI-Swift_Example', :exclusive => true do
  pod 'ORCommonUI-Swift', :path => '../'
end

target 'ORCommonUI-Swift_Tests', :exclusive => true do
  pod 'ORCommonUI-Swift', :path => '../'

pod 'ORCommonCode-Swift', '~> 0.3.1'

end
