source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ORCommonUI-Swift_Example', :exclusive => true do
  pod 'ORCommonUI-Swift', :path => '../'
end

target 'ORCommonUI-Swift_Tests', :exclusive => true do
  pod 'ORCommonUI-Swift', :path => '../'

  
end
