source 'https://bitbucket.org/omegarinc/cocoapods-specs.git' # private spec repo
source 'https://github.com/CocoaPods/Specs.git' # master cocoapods spec repo

use_frameworks!

target 'ORCommonUI-Swift_Example' do
  pod 'ORCommonUI-Swift', :path => '../'
end

target 'ORCommonUI-Swift_Tests' do
  pod 'ORCommonUI-Swift', :path => '../'

# pod 'ORCommonCode-Swift', '~> 3.0.0'

end
